# Generated by Django 2.2.2 on 2019-06-04 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ValueLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langvalues.Language')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langvalues.Value')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='values',
            field=models.ManyToManyField(through='langvalues.ValueLink', to='langvalues.Value'),
        ),
    ]
