# Generated by Django 2.2.2 on 2019-06-04 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langvalues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelink',
            name='factor',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
