# Generated by Django 2.2.2 on 2019-06-05 15:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langvalues', '0002_auto_20190604_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
