# Generated by Django 2.2.2 on 2019-06-05 17:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langvalues', '0003_language_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
